[project]
name = "mcp-server-relevance-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.12.2",
    "openai>=1.97.1",
    "python-dotenv>=1.1.1",
]
